-- V1: initial SouvenirPOS schema (baseline).
-- Generated from the JPA entities so `spring.jpa.hibernate.ddl-auto=validate` passes in
-- production. On an existing database (created earlier by ddl-auto=update), Flyway is
-- configured with baseline-on-migrate=true and treats this version as already applied.

create table categories (
    id   bigint generated by default as identity primary key,
    name varchar(255) not null unique
);

create table users (
    id                   bigint generated by default as identity primary key,
    name                 varchar(255) not null,
    username             varchar(255) not null unique,
    password_hash        varchar(255) not null,
    role                 varchar(255) not null check (role in ('OWNER', 'CASHIER')),
    token_version        integer default 0 not null,
    enabled              boolean default true not null,
    must_change_password boolean default false not null
);

create table sales (
    id             bigint generated by default as identity primary key,
    sale_date_time timestamp(6) not null,
    cashier_id     bigint not null,
    total_amount   numeric(12, 2) not null,
    payment_amount numeric(12, 2) not null,
    change_amount  numeric(12, 2) not null,
    constraint fk_sales_cashier foreign key (cashier_id) references users
);

create table sale_items (
    id          bigint generated by default as identity primary key,
    sale_id     bigint not null,
    category_id bigint not null,
    quantity    integer not null,
    unit_price  numeric(12, 2) not null,
    subtotal    numeric(12, 2) not null,
    constraint fk_sale_items_sale foreign key (sale_id) references sales,
    constraint fk_sale_items_category foreign key (category_id) references categories
);
